#!/bin/bash

tput setaf 3; echo "formatting code before committing"

## this will retrieve all of the .rs files that have been 
## changed since the last commit
STAGED_RS_FILES=$(git diff --cached --name-only -- '*.rs')

## we can check to see if this is empty
if [[ $STAGED_RS_FILES == "" ]]; then
tput setaf 4; echo "No Rust Files to Update"
## otherwise we can do stuff with these changed go files
else
    cargo fmt && git add .
fi

tput setaf 2; echo "done formatting"
tput sgr0 